version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: chatbot-db
    environment:
      MYSQL_ROOT_PASSWORD: 09012003
      MYSQL_DATABASE: chatbot
      MYSQL_USER: root
      MYSQL_PASSWORD: 09012003
    ports:
      - "3308:3307"
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: be
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3307/chatbot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 09012003
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
